library('dplyr')
library('stringr')
library('ggplot2')
files <- list.files('/home/lubonp/Downloads/train/')
setwd('/home/lubonp/Downloads/train/')
files <- data.frame(filename=files, stringsAsFactors = FALSE)
label_files <- files %>% filter(str_detect(filename, 'label'))
df_list <- list()
data_list <- lapply(label_files$filename,function(x)
{
  read.csv(x, header = FALSE, sep=' ')
})
data_list <- bind_rows(data_list, .id='file_no')
data_list$len <- data_list$V2 - data_list$V1
ggplot(data_list %>% filter(len<quantile(data_list$len, 0.999)), aes(x=len)) + geom_histogram(binwidth = 1)
x <- seq(from=0, to=1, by=0.0001)
y <- quantile(data_list$len, x)
quantile_df <- data.frame(x=x, y=y)
quantile(data_list$len, 0.997)
data_list_filtered <- data_list %>% filter(len<quantile(data_list$len, 0.997))
read_means <- data_list_filtered %>% group_by(file_no) %>% summarise(len=mean(len))
ggplot(read_means, aes(x=len)) + geom_histogram(binwidth = 1)
base_means <- data_list_filtered %>% group_by(V3) %>% summarise(len=mean(len))
ggplot(base_means, aes(x=len)) + geom_histogram(binwidth = 1)
cor(data_list_filtered$V1, data_list_filtered$len)
